
name: Test

on:
  workflow_dispatch:

env:
  FOO: bar


jobs:
  test-run:
  
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: S1
        run : |
          
          declare -a NAMES=(
            "BACKEND_TOKEN"
            "COS_ACCESS_KEY"
            "COS_ACCESS_KEY"
            "COS_SECRET_KEY"
            "GH_TOKEN_CLIENT_REPOS"
          )

          env="DEV"
          if [[ "$GITHUB_REF_NAME" == "demo" ]]; then
            env="DEMO"
          fi

          for name in "${NAMES[@]}"; do
           echo "$name=${env}_${name}" >> $GITHUB_ENV
          done
          
      - name: Echo
        run: |
          echo token = ${{ secrets[env.BACKEND_TOKEN] }}
          

